### ISSUE TITLE
Avatars for GHE?

### ISSUE THREAD

**Issue by jimkohl** [benbalter/jekyll-avatar#12]
Hi Ben,
Thanks for the nice gem.
It works nicely for public GH, but since its wired to avatars0.githubusercontent.com, its not finding avatars for any of our GHE users. 

Is there a way override the **host** in the gem to point to an equivalent for our GHE?
Thanks

**Comment by benbalter** [comment]
That's not currently possible, but should be easy to implement. To confirm, the domain is `avatars.example.com`, and the path is the same, correct? (e.g., `avatars.example.com/u/1234`).

**Comment by jimkohl** [comment]
Ben, thanks for the quick look.   Thinking more may be needed than a plugin.
  public GH  (works):       https://avatars.githubusercontent.com/hubot
  GHE (no subdomain!):   http://**avatars**.github.ACME.com/hubot

Does GHE (2.9) even support a domain and REST call for this currently?  
Or does our hosting team have to add it and/or install anything else?

**Comment by benbalter** [comment]
@jimkohl I *believe* as least for instances with subdomain isolation, it should just be a matter of setting the URL, which we can automatically pass to the build process (as we do with, e.g., Jekyll GitHub Metadata and Jekyll Mentions). I'm checking with the Avatars team to figure out what needs to be done for instances without subdomain isolation.

**Comment by jimkohl** [comment]
@benbalter forgive me if this is a newb question but since we are using github pages gem - that is pointing to your latest release which is v 0.4.2 which is 4 commits behind.  So ... since this helpful change you put in is contained in a portion of those commits ... what is the process for getting 0.4.3 published?   Do you release these on a time cycle?  Can I help with testing or anything?  Let me know.  Thanks much.

**Comment by benbalter** [comment]
@jimkohl I released version v0.5.0 (since it's a new feature). We can bump that in the Pages Gem so that avatars will work locally, but GitHub Enterprise is on a set release cycle, if that's what you're asking about?

**Comment by jimkohl** [comment]
yeah need Pages gem bumped to consume locally (as long as it won't break eprise) since 
I can't override version locally: gem 'jekyll-avatar',  '~> 0.5.0' without error.

Will keep lookout for appearance in eprise version soon.  thanks

**Comment by jimkohl** [comment]
Works great locally!  Will keep me eyes open for future GHE release containing this.
Thanks again!  Jim
