### ISSUE TITLE
GitHub Pages Build Fails

### ISSUE THREAD

**Issue by m1evankaiser** [benbalter/jekyll-avatar#14]
Just tried to add this to our GitHub pages jekyll site and, although it's listed in the [approved plugins list](https://pages.github.com/versions/), it caused our build to fail. Used version `0.5.0` as indicated in the list.

**Comment by archemiro** [comment]
I had the same issue after installing this plugin. The `travis ci` log:

```
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'vendor/bundle/ruby/2.4.0/gems/jekyll-3.6.2/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.
```

The plugin works fine on local installation.

**Comment by pathawks** [comment]
You will need to exclude `vendor/` from site build.

https://github.com/jekyll/jekyll/issues/2938
