### ISSUE TITLE
lazy image loading support

### ISSUE THREAD

**Issue by afeld** [benbalter/jekyll-avatar#15]
I am a frequent visitor to https://government.github.com/community/, which uses this plugin to display the avatars. The page takes 6.7 seconds to load on my relatively fast connection/machine, because there are 1065 images being requested.

In short, it would be great for jekyll-avatar to support lazy image loading. I've looked at [a](https://www.andreaverlicchi.eu/lazyload/) [few](https://appelsiini.net/projects/lazyload/) [plugins](https://luis-almeida.github.io/unveil/), and they all use the image URL in a `data-src` attribute (rather than `src`). Open to a pull request to support that?

cc @jbjonesjr

**Comment by benbalter** [comment]
@afeld 👍, so long as there's a fallback if the javascript library isn't loaded.
