### ISSUE TITLE
Error with avatars in for loops/variable-defined usernames

### ISSUE THREAD

**Issue by RDIL** [benbalter/jekyll-avatar#37]
### Describe the bug
Hi!
I just started a site on github pages with jekyll and this plugin.

(page is located at https://cakebot.club/contributors.html )

It seems that in production, all the rendered avatars are the first avatar in the data set, not the defined ones

### Steps to reproduce the behavior

1. Go to the link above
1. See error

### Expected behavior

The avatars should match the data given, not just mine.
@121jwang and @paramt 's avatars should be visible next to their names

### Additional context

My markdown:
```markdown
---
title: Contributors
layout: default
---

## Contributors

Cakebot would not be possible without the help, time, and dedication of the following people:

{% for contributor in site.data.contributors %}
  * {% avatar {{ contributor.github }} size=50 %} {{ contributor.name }} - @{{ contributor.github }}
{% endfor %}
```

data file (csv):
```csv
name,github
jumbo,RDIL
Tarsh,121jwang
Param,paramt
```

Thank you!

**Comment by AjitZero** [comment]
I'm facing the same issue.
I'm using this with:
```
{% for post in paginator.posts %}
  {% include post_preview.html %}
{% endfor %}
```
In `post_preview.html`, I've got:
```
{% avatar {{ author.social.github }} %}
```
which doesn't work, but this works:
```
{% avatar benbalter %}
```
So apparently, it takes only the first name's photo when used within a loop, but any fixed username call within the loop works just fine.

**Comment by RDIL** [comment]
@benbalter please take a look at this when you can :)

**Comment by benbalter** [comment]
Have you tried the `user=` format as described in https://github.com/benbalter/jekyll-avatar#passing-the-username-as-variable?

**Comment by RDIL** [comment]
I’ll give it a shot.  Thanks.

**Comment by RDIL** [comment]
Sadly, it didn’t work :(

> Have you tried the `user=` format as described in https://github.com/benbalter/jekyll-avatar#passing-the-username-as-variable?
> 
> > <img alt="" width="48" src="https://avatars0.githubusercontent.com/u/282759?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/4908d9947135e4536ef61d61512ee575f869bf6f/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e2e69636f"> GitHub**[benbalter/jekyll-avatar](https://github.com/benbalter/jekyll-avatar)**A Jekyll plugin for rendering GitHub avatars. Contribute to benbalter/jekyll-avatar development by creating an account on GitHub.

**Comment by RDIL** [comment]
Interesting, not sure what I did but it looks to be fixed now.

**Comment by kusma** [comment]
I'm seeing the same issue here. It seems to trigger when I use `{% avatar {{ foo }} %}` in a layout file, but not if I do it in an article. It's almost as if a variable gets cached from some previously rendered page or something like that.

**Comment by kusma** [comment]
Here's a reproduction case: https://github.com/kusma/jekyll-avatar-issue-37-repro

Render the reproduction, and observe that bar.html renders correctly, but foo.html gets the avatar from bar.html instead of the right one. I think that supports the caching hypothesis.

**Comment by ashmaroli** [comment]
@kusma Were you able to reproduce this issue with Jekyll 3.9?

**Comment by kusma** [comment]
Just tried, and no, it does not reproduce with Jekyll 3.9. So I guess there's some change in behavior in Jekyll 4.x that breaks this...

**Comment by kusma** [comment]
Since this seems unrelated to what the other users have experienced (Jekyll 4.x wasn't our in 2019), I decided to create a new ticked. So please ignore this ;)
