### ISSUE TITLE
Issue with custom variable for `user`

### ISSUE THREAD

**Issue by XhmikosR** [benbalter/jekyll-avatar#7]
So, I was trying to get this working, but I end up with the same image from the first loop item.

Code fragment

``` html
 <div class="row">
     <div class="col-md-12">
         <div class="list-group mpc-team">
           {% for member in site.data.team.active %}
             <div class="list-group-item">
               <iframe class="github-btn" src="https://ghbtns.com/github-btn.html?user={{ member.user }}&amp;type=follow" title="Follow {{ member.user }} on GitHub"></iframe>
               <a class="team-member" href="https://github.com/{{ member.user }}">
                  {% avatar {{ member.user }} size=32 %}
                  <strong>{{ member.name }}</strong> <small>@{{ member.user }}</small>
               </a>
             </div>
           {% endfor %}
         </div>
     </div>
 </div>
```

Output:
![screen shot 2016-02-27 at 13 12 03](https://cloud.githubusercontent.com/assets/349621/13372635/2b94b54e-dd54-11e5-913c-af46186d0764.png)

Full code https://github.com/mpc-hc/mpc-hc.org/tree/about

Am I missing something?

**Comment by XhmikosR** [comment]
I tried the same for Bootstrap (https://github.com/twbs/bootstrap/compare/v4-dev...v4-dev-docs), and I get the same results. Something seems weird @benbalter :/

**Comment by pathawks** [comment]
Can you try it without the extra braces?

```text
{% avatar member.user size=32 %}
```

**Comment by benbalter** [comment]
Also try `{% avatar user=member.user size=32 %}`

**Comment by XhmikosR** [comment]
Thanks both of you for the replies. I'll try it when I'm at home. BTW this
was taken from the Readme example.

**Comment by XhmikosR** [comment]
I tried both solutions, none of them works.

**Comment by benbalter** [comment]
One last try:

```
{% assign user = member.user %}
{% avatar {{ user }} %}
```

or 
```
{% assign user = member.user %}
{% avatar user=user %}
```

It's a quirk with our Liquid passes context to plugins.

**Comment by XhmikosR** [comment]
The last one works!
